### ISSUE TITLE
merge doesn't work

### ISSUE THREAD

**Issue by thorly** [gmtsar/gmtsar#21] opened 2020-04-20 02:09 UTC
Hello, I have a problem of merging data. I use p2p_S1_TOPS_Frame.csh to process Sentinel-1 data of Idaho earthquake.
The data are:
> S1A_IW_SLC__1SDV_20200407T013632_20200407T013656_032015_03B2C9_2AB4.SAFE S1B_IW_SLC__1SDV_20200320T013552_20200320T013619_020769_027618_9910.SAFE
> S1A_OPER_AUX_RESORB_OPOD_20200407T035944_V20200406T234559_20200407T030329.EOF
> S1B_OPER_AUX_POEORB_OPOD_20200409T110831_V20200319T225942_20200321T005942.EOF

When p2p_S1_TOPS_Frame.csh done, **I check the merge directory, I found some space  between two swath**. like this:
![Screenshot from 2020-04-20 10-05-40](https://user-images.githubusercontent.com/32875029/79707353-cbb9cc00-82ee-11ea-949a-42dd94967d05.png)

**Comment by Xiaohua-Eric-Xu** [comment] 2020-04-20 02:15
Hi Leiyuan,
Is it possible for you to share the dataset you used for us?
Cheers,
Xiaohua(Eric)

**Comment by thorly** [comment] 2020-04-20 02:20
what data？raw data, or else?

**Comment by thorly** [comment] 2020-04-20 02:20
what data？raw data, or else?

**Comment by Xiaohua-Eric-Xu** [comment] 2020-04-20 02:21
If you could share your .SAFE, .EOF and dem.grd, I could try to reproduce your results here.

**Comment by Xiaohua-Eric-Xu** [comment] 2020-04-20 02:22
p.s. Did you re-assemble the data your these are directly from ASF/ESA?

**Comment by thorly** [comment] 2020-04-20 02:26
one from ASF, one from ESA

**Comment by thorly** [comment] 2020-04-20 02:33
I will upload data to my google drive, wait some minutes.

**Comment by Xiaohua-Eric-Xu** [comment] 2020-04-20 02:35
OK, I'll give it a check, probably tomorrow sometime.

**Comment by thorly** [comment] 2020-04-20 03:06
You can download data from here(https://drive.google.com/drive/folders/1ay8c6-RuiFSg1dljJFSqZBvUm6sHPjGw?usp=sharing).

**Comment by Xiaohua-Eric-Xu** [comment] 2020-04-20 20:23
I believe this is because the data has extra-large range shifts. The swath overlap is around 2km where the shift is about the same value. When checking each individual interferogram from each subswath, they have quite a large vacant area at the boundary.

F1/raw/S1_20200407_013632_F1.PRM:rshift =  -831 
F2/raw/S1_20200407_013633_F2.PRM:rshift =  -772 
F3/raw/S1_20200407_013634_F3.PRM:rshift =  -697 

See attached screenshot:
screenshot: merged and geocoded
screenshot: individually geocoded

Even with individually geocoded results, there is a small area of no-data in the image between subswaths. GMTSAR assumes TOPS data capable of performing interferometry within each subswath. One way on fixing this problem might be 

1) read the SLC as complex short integer;
2) write real and imaginary parts into netcdf grids. (search grdwrite2.m)
3) try merge the SLC product with merge_swath (do produce a new PRM)
4) run coregistration following align_tops.csh
5) perform interferometry.

This probably will not work without removing the ramp due to the sweeping antenna from the data. And for now I don't think we have a module to do that, as the deramp function parameters from the data may not be good enough (check make_s1a_tops.c).

Maybe you could just run grdblend on the individually geocoded product? Go to each F?/intf/* folder run the following

ln -s ../../topo/trans.dat .
proj_ra2ll.csh trans.dat phasefilt.grd phasefilt_ll.grd
grd2kml.csh phasefilt_ll phase.cpt

Then use apply grdblend on the phasafilt_ll.grd-s.

![screenshot1](https://user-images.githubusercontent.com/16844111/79796150-e77e9b80-8309-11ea-9f93-4832789c329a.jpg)
![screenshot2](https://user-images.githubusercontent.com/16844111/79796193-f9603e80-8309-11ea-8b93-9aa4e714ff03.jpg)

**Comment by dsandwell** [comment] 2020-04-20 20:30
This is very interesting.  Why are these data range shifted.   Why don’t we see this in other areas?

> On Apr 20, 2020, at 1:24 PM, Xiaohua(Eric) Xu <notifications@github.com> wrote:
> 
> 
> I believe this is because the data has extra-large range shifts. The swath overlap is around 2km where the shift is about the same value. When checking each individual interferogram from each subswath, they have quite a large vacant area at the boundary.
> 
> F1/raw/S1_20200407_013632_F1.PRM:rshift = -831
> F2/raw/S1_20200407_013633_F2.PRM:rshift = -772
> F3/raw/S1_20200407_013634_F3.PRM:rshift = -697
> 
> See attached screenshot:
> screenshot: merged and geocoded
> screenshot: individually geocoded
> 
> Even with individually geocoded results, there is a small area of no-data in the image between subswaths. GMTSAR assumes TOPS data capable of performing interferometry within each subswath. One way on fixing this problem might be
> 
> 	• read the SLC as complex short integer;
> 	• write real and imaginary parts into netcdf grids. (search grdwrite2.m)
> 	• try merge the SLC product with merge_swath (do produce a new PRM)
> 	• run coregistration following align_tops.csh
> 	• perform interferometry.
> This probably will not work without removing the ramp due to the sweeping antenna from the data. And for now I don't think we have a module to do that, as the deramp function parameters from the data may not be good enough (check make_s1a_tops.c).
> 
> Maybe you could just run grdblend on the individually geocoded product? Go to each F?/intf/* folder run the following
> 
> ln -s ../../topo/trans.dat .
> proj_ra2ll.csh trans.dat phasefilt.grd phasefilt_ll.grd
> grd2kml.csh phasefilt_ll phase.cpt
> 
> Then use apply grdblend on the phasafilt_ll.grd-s.
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by Xiaohua-Eric-Xu** [comment] 2020-04-20 20:35
I think we only see this in very unoften cases when the swath is very long (e.g. > 500-1000km), and the valid samples start and end at inconsistent locations in the image.

**Comment by thorly** [comment] 2020-04-21 00:45
> I believe this is because the data has extra-large range shifts. The swath overlap is around 2km where the shift is about the same value. When checking each individual interferogram from each subswath, they have quite a large vacant area at the boundary.
> 
> F1/raw/S1_20200407_013632_F1.PRM:rshift =  -831 
> F2/raw/S1_20200407_013633_F2.PRM:rshift =  -772 
> F3/raw/S1_20200407_013634_F3.PRM:rshift =  -697 
> 
> See attached screenshot:
> screenshot: merged and geocoded
> screenshot: individually geocoded
> 
> Even with individually geocoded results, there is a small area of no-data in the image between subswaths. GMTSAR assumes TOPS data capable of performing interferometry within each subswath. One way on fixing this problem might be 
> 
> 1) read the SLC as complex short integer;
> 2) write real and imaginary parts into netcdf grids. (search grdwrite2.m)
> 3) try merge the SLC product with merge_swath (do produce a new PRM)
> 4) run coregistration following align_tops.csh
> 5) perform interferometry.
> 
> This probably will not work without removing the ramp due to the sweeping antenna from the data. And for now I don't think we have a module to do that, as the deramp function parameters from the data may not be good enough (check make_s1a_tops.c).
> 
> Maybe you could just run grdblend on the individually geocoded product? Go to each F?/intf/* folder run the following
> 
> ln -s ../../topo/trans.dat .
> proj_ra2ll.csh trans.dat phasefilt.grd phasefilt_ll.grd
> grd2kml.csh phasefilt_ll phase.cpt
> 
> Then use apply grdblend on the phasafilt_ll.grd-s.
> 
> ![screenshot1](https://user-images.githubusercontent.com/16844111/79796150-e77e9b80-8309-11ea-9f93-4832789c329a.jpg)
> ![screenshot2](https://user-images.githubusercontent.com/16844111/79796193-f9603e80-8309-11ea-8b93-9aa4e714ff03.jpg)
> 
> 

Thank you

**Closed** 2020-05-08 00:26 UTC
