### ISSUE TITLE
[Help]: some questions about organize_files_tops.csh

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#385] opened 2022-07-23 11:24 UTC
I see some weird points where possibly I just missed something:

There is the first question: is it possible to have two consecutive scenes on overlapping areas (one before midnight and one after it) so the scene start dates are different? The code supposes it's not possible but I'm not sure about it.

Also, the processing accuracy looks relative to a scene size but we create a single PRM file instead of a set of PRM files for the original scenes. Is it a limiting factor for the real computation?

**Comment by Xiaohua-Eric-Xu** [comment] 2022-07-25 16:04
This could be an issue. @ericlindsey has met this issue before I think. For such cases, create_frame_tops.csh will still work. The problem is how to determine the tracks are consecutive ones. I know one could use some time tools to do so to replace the lines of 57-67 in the organizing scripts, but haven't got time to do so. 

For a single PRM, if I understand correctly, you are worried about the baseline? For at least 2km long scenario, the baseline assumption is still good based on our earlier estimates. The relatively more concerning scenario is when the orbits are not fully parallel to each other, which is a fundamental issue for baseline assumption. It may create a ramp of ~0.04-0.12 mm/yr.

**Comment by ericlindsey** [comment] 2022-07-25 16:49
I can't remember if I met this particular issue! I know I did encounter a problem when scenes occurred on Jan 1, there was some inconsistency between date calculations that called this Julian day 001, or decimal year 000.x. I think this has been fixed though.

**Comment by mobigroup** [comment] 2022-07-26 06:53
Great, thanks! I'm working on easy way to define pins to reframe scenes like to:

```
pins = [[45.8, 34.6], [45.8, 35.2]]
or
pins = [None, [45.8, 35.2]]
or
pins = [45.8, 34.6, 45.8, 35.2]
or
pins = [None, None, 45.8, 35.2]
or
pins = None
```
![Screen Shot 2022-07-26 at 13 29 09](https://user-images.githubusercontent.com/7342379/180938729-17338ef3-d998-44f3-ade6-ae4846997d72.jpg)

So the pins auto-detected placement on the frame continuations should be safe and it looks human readable I think. Also, we are able automatically swap pins for descending orbit to simplify the pins management (pin1.latitude < pin2.latitude for the both orbits).

And about one more point. GMTSAR allows to merge sub swaths but I'm not sure if it's useful addition for PyGMTSAR. The point is we need too much RAM for the processing on multicore systems. For the example, on Apple Silicon iMac we are limited 16 GB RAM and on Air M2 24 GB RAM for 8 cores and on standalone cloud instances like to Amazon EC2 or Google Cloud VM and AI Notebook the most common configuration provides 32 GB RAM for 8 cores (MacOS uses RAM compression and 16 GB RAM on Mac is about comparable to 32 GB RAM on Linux... I tried RAM compression on Linux many years ago and it was not stable to use and it still not available out from the box on Debian and Ubuntu)... usually that's enough for a single subswath processing only. At the same time, separate subswaths unwrapping sometimes produces vertical offsets due to unwapping ambiguity (which can be fixed easy of course). So I doubt a bit is it a useful case to merge subswaths?

**Comment by Xiaohua-Eric-Xu** [comment] 2022-07-26 15:17
@mobigroup , phase unwrapping is a global solution and is dependent on the topology of residues. It does not matter much if the AOI is localized or small. But imagine an earthquake rupture that spreads to multiple subswaths. In this case, merging first is the better solution I think.

**Comment by mobigroup** [comment] 2022-07-26 15:46
@Xiaohua-Eric-Xu Yes, while an earthquake rupture spreads to multiple scenes on different paths too. About the phase unwrapping we have consistent values for a single unwrapping but inconsistent for separate unwrapping. Anyway, it's not a problem to fix when the images overlapping.

**Comment by ericlindsey** [comment] 2022-07-26 16:39
It's definitely important to keep the ability to merge before unwrapping, even if it's not used in all cases. It's true that it's easy to merge after unwrapping if you have a single offset of n*2pi between two subswaths, but not if one of the subswaths has multiple unwrapping errors inside it. In such a case, it's often very helpful to merge first and then unwrap, since the unwrapper can often link up the two disconnected parts of the bad subswath when there is a pathway around it. E.g. imagine that you have a lake which fully crosses one subswath but not the other two. In the same way, unwrapping is more stable when merging along-track first as well. Unfortunately you're right that trying to unwrap a very large frame like your example above after merging becomes a RAM issue. At least RAM costs are slowly going down. Snaphu used to have to be run on many individual patches of the image, one at a time. Someday we may decide to process whole orbits at a time!

**Comment by mobigroup** [comment] 2022-07-26 16:50
@ericlindsey Thanks a lot, I see now the reasons! By the way, snaphu tiles parallel processing sometimes returns incorrect results to me even using a half of the tile overlapping (and for this case overhead is inappropriate). The reason is the same as you mentioned above - full image unwrapping is more robust.

**Comment by chintals** [comment] 2022-07-26 20:25
@ericlindsey Have you used Snaphu command with -S flag (single-tile reoptimization after multi-tile init)? Essentially run snaphu in parallel on patches of unwrap grid and use the merged unwrapped tiles as initialization to a single-tile optimization that produces the final unwrapped output. I have seen some good speedup in unwrapping. However, the Tile control portion (NTILEROW, NTILECOL, ROWOVRLP, COLOVRLP, NPROC, TILECOSTTHRESH, MINREGIONSIZE) in snaphu.conf.brief needs to be unchecked and updated.  As well as adding -S flag to snaphu command in snaphu_interp.csh.

**Comment by ericlindsey** [comment] 2022-07-26 20:45
@chintals I have not tried this, it sounds interesting! Do you know if this option results in reduced RAM usage, or simply a speedup? Are there any cases where it is not recommended?

**Comment by chintals** [comment] 2022-07-26 21:13
@ericlindsey when you enable -S flag Snaphu optimization runs on each tile individually and uses much less memory and time compared to snaphu optimization on a complete grid (or single tile). After individually unwrapping the tiles, it uses the overlap (in pixels) parameter to estimate offset from adjacent tiles, and then reconstructs a merged unwrap tile, which is then used as initialization for single tile unwrapping.
From my experience, its uses less memory overall. I have noticed in area of large gaps and poor coherence, single tile unwrapping tends to hang and finish slowly, while tile control lets you get over that hurdle.

The description for tile control is provided in the [snaphu.conf.brief](https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/snaphu.conf.brief)

**Comment by mobigroup** [comment] 2022-07-27 05:44
@chintals Did you check unwrapping on a reduced resolution interferogram too? For me it’s as faster as more correct than tiles snaphu unwrapping with any options.

By the way, PyGMTSAR allows to define custom snaphu parameters without any hassle (see examples in the Jupyter Notebooks on GitHub and Google Colab).

**Comment by mobigroup** [comment] 2022-07-27 10:23
@chintals @ericlindsey Actually that's easy to test in PyGMTSAR using custom SNAPHU configuration:
```
# generate a custom snaphu config file
conf = sbas.PRM().snaphu_config(defomax=DEFOMAX, NTILEROW=4, NTILECOL=4, ROWOVRLP=200, COLOVRLP=200)
# run only one unwrapping task at the time because the custom SNAPHU configuration already uses all the cores
sbas.unwrap_parallel(pairs, n_jobs=1, threshold=CORRLIMIT, func=cleaner, conf=conf)
```
Let's compare full unwrapping vs tiled unwrapping times (execution times marked at the progress bars):

![Screen Shot 2022-07-27 at 17 10 54](https://user-images.githubusercontent.com/7342379/181224079-0a715eec-4545-482b-87ca-6c66ddedda63.jpg)

As you see, the unwrapping is 6 times faster (24s vs 146s) on 8 core Apple iMac M1. But the result is a bit different:
the full unwrapping produces range [-150 mm, 875 mm] vs tiled unwrapping range [-150 mm, 858 mm]. So yes, tiled unwrapping is much faster but no it does not return the same results!

**Comment by chintals** [comment] 2022-07-27 15:43
@mobigroup I have checked snaphu serial, and snaphu tiled against 4/1 and 8/2 decimation for sentinel interferograms. Besides the obvious speedup (technically longer processor times, but reduced wall clock times), the results are slightly different. I was checking the difference in the grd files with grdmath and histogram method, rather than looking at range of the unwrapped grd files. One significant benefit for tiled unwrapping for me was in an area of vegetation (poor coherence), with optimal tile control parameter, , snaphu tiled unwrapping took about ~1 hour, compared to 24+ hours for snaphu serial unwrapping for a single frame (3 merged subswaths). For most of the 24 hours snaphu serial was barely using any processor, memory or IO resources. 

If reducing/remove unwrapping error is key then besides removing phase ambiguities after unwrapping, one could implement [3d snaphu unwrapping](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.456.390&rep=rep1&type=pdf), [Git](https://github.com/dbekaert/StaMPS/blob/master/matlab/uw_3d.m). It is better suited for pythonic implementation than a GMT based implementation.

Also I am curious as to the impact of the gaussian, adpative goldtsein filters altering phase information during interferogram generation (gaussian filter kernal does not change with different range/azi decimation). I understand adaptive goldstein is needed for sharper fringes, and reduce fuzziness which would cause unwrapping issues.  And GMTSAR does generates corr_filt.grd along with phasefilt.grd, but we use corr.grd as input for snaphu unwrapping. 

@mobigroup sorry for taking your thread offtopic, but curious to hear @Xiaohua-Eric-Xu @ericlindsey and your thoughts on interferogram generation and unwrapping as well.

**Comment by chintals** [comment] 2022-07-27 16:08
> @chintals Did you check unwrapping on a reduced resolution interferogram too? For me it’s as faster as more correct than tiles snaphu unwrapping with any options.
> 
> By the way, PyGMTSAR allows to define custom snaphu parameters without any hassle (see examples in the Jupyter Notebooks on GitHub and Google Colab).

That is pretty cool. I believe you cannot pass the tilecostthresh, and minregionsize as parameter flag when using snaphu command

**Comment by mobigroup** [comment] 2022-07-27 16:16
@chintals 
> That is pretty cool. I believe you cannot pass the tilecostthresh, and minregionsize as parameter flag when using snaphu command

But what is the problem?! Sure, we can pass any SNAPHU parameter by the same way even not existing parameter "AHAHA":
```
conf = sbas.PRM().snaphu_config(defomax=DEFOMAX,
                                NTILEROW=4, NTILECOL=4, ROWOVRLP=200, COLOVRLP=200,
                                TILECOSTTHRESH=500, MINREGIONSIZE=100,
                                AHAHA=0)
```

**Comment by mobigroup** [comment] 2022-07-27 16:55
@chintals Would you explain why these parameters are important for you? Are the default values bad by some reason? I'm preparing one new example Jupiter notebook for PyGMTSAR and it might be good addition to explain tiled unwrapping too.

**Comment by mobigroup** [comment] 2022-07-28 11:46
This is the Jupiter notebook where custom SNAPHU configurations and parallel unwrapping explained:
[ASF_Downloading_2017_Iran–Iraq_Earthquake_Co_Seismic_Interferogram.ipynb](https://colab.research.google.com/drive/1RfOIcwf-GkVNdTad9XDJ-torZ-Hqg9In?usp=sharing)

Use Alaska Satellite Facility (ASF) credentials to download the original scenes from ASF datastore (link to register on ASF is provided in the notebook). The results are compared to the original GMTSAR, GAMMA and SNAP software packages.

<img width="1160" alt="Screen Shot 2022-07-28 at 17 26 34" src="https://user-images.githubusercontent.com/7342379/181497375-73dc7c47-7acc-493d-a5ca-262e9b25775a.png">

**Closed** 2023-11-30 02:34 UTC
