### ISSUE TITLE
[Help]: organize_files_tops_linux.csh

### ISSUE THREAD

**Issue by 674111501** [gmtsar/gmtsar#141] opened 2021-05-13 23:58 UTC
**Describe the problem you met**
Hi,Mr. Xu
There is a problem when I run organize_files_tops_linux.csh. The order is organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1.When I run it,the terminal will tell me that "Combing /home/see/DZ/asc/data/S1A_IW_SLC__1SDV_20150730T101156_20150730T101224_007039_009912_6FA1.SAFE ...
if: Expression Syntax."I don't know how I can reslove this problem.

![屏幕截图 2021-05-14 074707](https://user-images.githubusercontent.com/69631148/118201473-16722d00-b48a-11eb-8690-5e3b54457a61.png)

**Comment by Xiaohua-Eric-Xu** [comment] 2021-05-14 00:03
Oh no, this strange error again... I met this a couple of times and haven't got a clue why this happens. We could not reproduce this on our end. It should be one of the if statement but this error comes and goes. If in any way I could access your machine, it may be possible for me to figure this out.

**Comment by 674111501** [comment] 2021-05-14 00:35
Sorry，Mr. Xu.I can't connect with Github.I have download the software&nbsp;sunloginclient.Do you use it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaohua(Eric) ***@***.***&gt;; 
发送时间: 2021年5月14日(星期五) 上午8:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gmtsar/gmtsar] [Help]: organize_files_tops_linux.csh (#141)





 
Oh no, this strange error again... I met this a couple of times and haven't got a clue why this happens. We could not reproduce this on our end. It should be one of the if statement but this error comes and goes. If in any way I could access your machine, it may be possible for me to figure this out.

**Comment by 674111501** [comment] 2021-05-14 01:36
HI,Mr. Xu.I think I have find where the problem is.In orbit.list,there are two orbit files.If you delete one of two orbit files,the problem is solved.
![终端](https://user-images.githubusercontent.com/69631148/118207364-17f62200-b497-11eb-9704-7dcb5a39e2af.png)
![脚本](https://user-images.githubusercontent.com/69631148/118207427-352af080-b497-11eb-9f1d-98a72bd73934.png)
![orbitlist](https://user-images.githubusercontent.com/69631148/118207547-80450380-b497-11eb-8a60-350ea3b7b4f0.png)

**Comment by 674111501** [comment] 2021-05-14 01:45
Hi,Mr. Xu. I think I have find where the problem is. In orbit.list,there are two orbit files for one day.If you delete one of two, it will success to run.
![终端](https://user-images.githubusercontent.com/69631148/118208296-1299d700-b499-11eb-997b-d51c6a2bfdf3.png)
![脚本](https://user-images.githubusercontent.com/69631148/118208306-188fb800-b499-11eb-96f5-2d51127f2075.png)
![orbitlist](https://user-images.githubusercontent.com/69631148/118208316-1c233f00-b499-11eb-9a8f-7db61ace38d1.png)

**Comment by Xiaohua-Eric-Xu** [comment] 2021-05-14 18:09
Great! I marked this as `Solutions`. It's been puzzling us for a while.

**Comment by 674111501** [comment] 2021-05-15 03:20
Thank you,Mr. Xu!

**Closed** 2021-05-15 03:21 UTC
Labels: Solutions

**Comment by Xiaohua-Eric-Xu** [comment] 2021-06-07 18:07
Here's what Caleb proposed as a solution: http://gmt.soest.hawaii.edu/boards/6/topics/8652?r=8658#message-8658

Caleb wrote:
> Hi Eric,
> 
> Yes, it was the same problem. Only that there were a lot more duplicates in my case. Removing them solved the problem. 
> 
> Thanks a million for the help!!!!
> 
> PS: I have added the python script that I used to remove duplicates. I tried doing this in bash script, but I couldn't manage it. I have attached the bash script and orbits.list. If anyone can help make it work, that would be great!
> 
> *EDIT: I managed to get the bash script to work. It does take a long time though...*


With attached scripts: 

[orbits.list.txt](https://github.com/gmtsar/gmtsar/files/6611108/orbits.list.txt)
[removeDuplicates2.sh.txt](https://github.com/gmtsar/gmtsar/files/6611109/removeDuplicates2.sh.txt)
[removeDuplicates.sh.txt](https://github.com/gmtsar/gmtsar/files/6611110/removeDuplicates.sh.txt)
[removeDuplicates.py.txt](https://github.com/gmtsar/gmtsar/files/6611111/removeDuplicates.py.txt)
