### ISSUE TITLE
[Feature]: Should't organize_files_tops_linux.csh call download_sentinel_orbits_linux.csh?

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#573] opened 2022-11-24 18:45 UTC
It seems redundant to have two scripts downloading orbits, why doesn't the organize script use the download script? Also the organize script says it doesn't support RESORB while the download script does.

Suggestion: Either remove download orbit functionality from organize script and expect running download orbits script beforehand, or call it within organize scrip itself.

**Comment by Xiaohua-Eric-Xu** [comment] 2022-11-25 05:06
Short answer: they were written by two developers.

Long answer: When I first wrote the organizing script, I was using orbits from the UNAVCO server which is now disabled I think, and the restituted orbit product was not so great (early version? they reprocessed some I think). And since the total size of all precise orbit product was pretty small, I didn't care and just downloaded all of them, thinking that we don't really need restituted orbits. Then as res-orb gets better and folks want faster data after events, restituted orbits are becoming an option for create_frame_tops.csh (which means for occasional use). Then we found a lot of new users will chose wrong orbit and complain to us so we had Katherine wrote an orbit downloading script. 

I think the newest version calls downloading query inside the script but I am not sure whether that only support precise orbits. @kguns32 . Could we add res-orb as an option to organize_files_tops[_linux].csh?

**Comment by SteffanDavies** [comment] 2022-11-25 13:59
> Short answer: they were written by two developers.
> 
> Long answer: When I first wrote the organizing script, I was using orbits from the UNAVCO server which is now disabled I think, and the restituted orbit product was not so great (early version? they reprocessed some I think). And since the total size of all precise orbit product was pretty small, I didn't care and just downloaded all of them, thinking that we don't really need restituted orbits. Then as res-orb gets better and folks want faster data after events, restituted orbits are becoming an option for create_frame_tops.csh (which means for occasional use). Then we found a lot of new users will chose wrong orbit and complain to us so we had Katherine wrote an orbit downloading script.
> 
> I think the newest version calls downloading query inside the script but I am not sure whether that only support precise orbits. @kguns32 . Could we add res-orb as an option to organize_files_tops[_linux].csh?

Ideally it would download precise orbits and then restituted orbits for any missing products (< 20 days) instead of 2 different modes. I don't see much point in downloading resorbs for products that have precise orbits available.

**Comment by kguns32** [comment] 2022-11-28 19:00
Hi guys -- yes for sure, we can add that functionality! I would suggest we add a warning for any downloads of restituted orbits though, just so whoever uses gets restituted orbits knows they should go back and reprocess with precise orbits when they become available (I am thinking of newer users who might not think much of it if everything is downloaded automatically for them). I think that is originally why I didn't implement it straight-off.

**Comment by mobigroup** [comment] 2022-12-19 18:47
There is the well-known tool to download the both kinds of Sentinel-1 orbits: https://pypi.org/project/sentineleof/ It’s documented and works. What is the reason to have instead the custom incomplete scripts in GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-19 23:23
Well, you may have neglected the time domain when deriving the reasoning. One highly possible reason could the script (before added to GMTSAR) was written when there's no such script.

sentineleof
![image](https://user-images.githubusercontent.com/16844111/208546608-8eaf7d8b-87df-442e-bff3-59698bf66205.png)

gmtsar
![image](https://user-images.githubusercontent.com/16844111/208546740-bc5f556b-f48f-4074-ae32-00f5f12ad5d4.png)

my own
![image](https://user-images.githubusercontent.com/16844111/208546938-f842ba31-50df-4add-bb8c-a5c6b08e9a26.png)

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-20 05:19
When users are at your level, usually they already feel comfortable taking parts from the code/script and make it their own :), and they'll find their "best" scripts/code. Just like lots of modules in a certain software (like gmt maybe) have other or more advanced algorithms to implement, but as long as the code does the job, that's fine with me. If I really hate something, I'll just re-write it.

**Comment by mobigroup** [comment] 2022-12-20 05:41
When we speak about the tools reproducibility and predictability that’s required to have the exact behavior: the code needs to produce the expected output always and independently of the current timestamp (and orbit files names) too. And we need to have it yesterday but not tomorrow. Do you still prefer to make your own script? Ok, but it can’t be robustly coded on shell because shell time processing is not platform agnostic and by my experience there is no way to build stable time processing scripts for all platforms. It will be problematic on a new shell version or on a new platform and so on. Are you ready to suffer users by your code on Apple Silicon Ubuntu 18 for an example? Sure, you are not able to test all the possible environments. For now you provide the great software which is extremely hard to use  - please think a bit about GMTSAR usability too. I follow the tickets and see how the usability issues frustrate users again and again and you spend a lot of time to discuss the same issues for years.

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-20 05:59
I understand what you mean, ideally if we have lots of lots of time to constantly update with everything, that's a great way, yet that rarely is the case for us. e.g. I think you meant the multiple definition issue, but I don't think I have that much amount of time to go through all previous code to fix it, unless I am on sabbatical?

The choices you are suggesting (an orbit downloading script from others when it's easy enough to code up by ourselves) are not as what you are indicating through lines (reliability?). Current software designs ask developers to build upon others work, yet complicating the dependencies will make the software fragile, i.e. once a small piece breaks, the whole thing may stop working. You don't want to comeback and examine something not under your control after things become problematic though that's mostly the scenario (e.g. the update of c compilers with ubuntu). It's lucky and unlucky for us that shell is pretty much dead. However, when a specific update breaks the chain and the affected package we chose are not updating anymore with it, that's when we are in deep trouble.

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-20 06:04
We have someone who's helping us making an "environment" to make sure installations are the same across platforms, maybe that'll help with what you meant?

**Comment by mobigroup** [comment] 2022-12-20 06:38
Ahh, PyGMTSAR uses GMTSAR binaries (only) under the hood - is it fragile by this way and should we completely remove all the GMTSAR dependencies to make it better?:) You see GMTSAR as a monolithic software while I speak about splitting it for packages following unix way. Sentineleof package is simple and easy to fix or modify if needed - actually that’s much more easy than find the related code inside GMTSAR scripts and fix it and check how the whole software works after that. Just one question- do you have automatic tests (CI) for the orbits downloading feature inside GMTSAR? If not thats the reason to have a separate package for this feature.

P.S. I even think that’s more easy to rewrite GMTSAR on Python and make Python autotests for Ubuntu and MacOs rather than make autotests for GMTSAR console scripts. For now, PyGMTSAR CI tests produce a lot of pictures on Ubuntu 18,20,22 and MacOs 11, 12 for Python 3.7, 3.8, 3.9, 3.10 (3 x 4 + 2 x 4 = 20 environment combinations in total) and all the plots for the tests for every commit available for 90 days on GitHub, see Artifacts sections here: https://github.com/mobigroup/gmtsar/actions Do you still afraid about the 3rd party dependencies? Ok, Docker images available for popular OSes and provide reproducible environments - all the dependencies and sources are already compiled and tested, see https://hub.docker.com/r/mobigroup/gmtsar In case when even all the dependencies are broken and you have no ability to fix them you are still able to use the Docker images without any hassle on any platform. Is it “fragile“?

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-20 07:00
Like I said, your suggestion's good, but I am not sure we have the time to complete all of that. So the priority falls to a concave where minimal amount of work is needed for the long run, unless, someone like you are willing to help us (like the CI tests you built).

If you are suggesting virtual systems (like Docker, at a time-stamp) being solutions, we already have that (virtual images) distributed. And likely we could distribute under any given systems.

The end-to-end tests we do are mostly on local machines from compiling to processing every exemplary datasets we have (~ 15-ish over satellites ERS1/2, ENVISAT, ALOS-1/2, RadarSat2, CSK, TSX, Sentinel-1, ...), which takes about a whole day to run. And being able to compile does not necessarily mean the solution are the same as before, especially after some time's development. This is not CI testing and I am not sure Github allows processing them over all common systems. Maybe virtual systems for testing?

**Comment by mobigroup** [comment] 2022-12-20 07:30
By my opinion you would save a lot of time using the modern tools. In addition, it provides much better user experience too.

GitHub actions CI tests allow to run some complex tests like to this one:
https://github.com/mobigroup/gmtsar/blob/master/tests/S1A_Stack_CPGF_T173.py The test reproduces your example Stack_CPGF_T173.tar.gz and checks a lot of cases and plots all the results plus adds PyGMTSAR detrending and spatial filtering and SBAS processing. So the successful test means the code is compiled well and it works as expected too. When you need to check the results visually just open the Artifacts section for the recent commit or any other and download all the plots for any test environment as zip archive: https://github.com/mobigroup/gmtsar/actions/runs/3612151287
Sure, there are some processing limits like to 2 cores and 6 hours for a single task. That’s enough to perform even SBAS processing on a few bursts for a dozen of interferograms (~30 minutes for the example Stack_CPGF_T173.tar.gz) or a few full scene interferograms (<1 hour for one full scene interferogram, see https://github.com/mobigroup/gmtsar/blob/master/tests/S1A_2016_Kumamoto_Earthquake.py).

Virtual machines are not available for all the architectures today while Docker is ready to use almost everywhere. Also, it looks more straightforward when you just need to run a Docker Desktop application and open your web browser to work. That’s exactly the same as Google Colab environment in your web browser.

And yes, some users prefer Google Colab to run the processing on the free cloud environment without any hassle with the software installation and disk space and RAM availability. JupyterLab web interface is the best for Python programming but it allows to run shell commands and show output pictures too. We are able to replace the old-school user manuals by the new interactive notebooks.

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-20 08:39
> By my opinion you would save a lot of time using the modern tools. In addition, it provides much better user experience too.

Maybe you are right, but I need to learn how to use them and other developers hopefully too. No guarantee here.

> Sure, there are some processing limits like to 2 cores and 6 hours for a single task. That’s enough to perform even SBAS processing on a few bursts for a dozen of interferograms (~30 minutes for the example Stack_CPGF_T173.tar.gz) or a few full scene interferograms (<1 hour for one full scene interferogram, see

What you meant is TOPS data, there are others like ALOS-2 ScanSAR that's 50GB per image... 

> Virtual machines are not available for all the architectures today while Docker is ready to use almost everywhere.

Time to learn? And potentially for future uses too.

> That’s exactly the same as Google Colab environment in your web browser.

Not everywhere can access that. 

> JupyterLab web interface is the best for Python programming but it allows to run shell commands and show output pictures too.

I think we are turning toward that direction for tutorial purposes.

**Comment by mobigroup** [comment] 2022-12-20 09:03
Don’t worry I have the answers when we speak about the technical difficulties.

> …ALOS-2 ScanSAR that's 50GB per image...

That’s possible to configure GitHub actions to be runned on your own hosts without the limitations. Also, GitHub limits could be extended using paid subscription or for some open source projects I think (you’d ask for it).

> Time to learn? And potentially for future uses too.

Docker Desktop provides virtualization and containerization in one click even on Apple Silicon (or Linux arm 32/64) hosts. VirtualBox and others are just in beta versions on Apple Silicon. Probably the users will select some other InSAR software for months or years waiting for VirtualBox release on Apple Silicon.

> Not everywhere can access that.

Yes, so we can provide the same experience on Google Colab and in Docker Containers and with local installation.

And one more point. I’m really disappointed when even GMTSAR commiters on high grade hardware are not able to perform multi-scene processing. It looks as the big problem when GMTSAR tools can process this amount of data using just 16 GB RAM without swap (in Docker container) on Apple Air laptop but it doesn’t possible for all  GMTSAR users due to lack of usability. Maybe a little bit education to use the modern approaches is valuable?

**Comment by Xiaohua-Eric-Xu** [comment] 2022-12-20 11:36
> Maybe a little bit education to use the modern approaches is valuable?

As part of our proposal, we are on the way of constructing a searchable documentation page. It is not completed yet, both format and content. (a crude test is here https://gmtsar.github.io/index.html) In the future there should be detailed documentation on every module and scripts with usable examples.

**Comment by omarwater98** [comment] 2023-01-20 17:09
@Xiaohua-Eric-Xu Hi Professor, im trying to download precise orbits but i have this problem, did you know how i coul solved?

 ./download_sentinel_orbits.csh SAFE_filelist 1


 Downloading Precise Orbits (POEORB)...
 
--------------------- 
Finding orbits for S1A_IW_SLC__1SDV_20220128T124140_20220128T124207_041661_04F4DD_F734.SAFE...
date: invalid option -- 'v'
Try 'date --help' for more information.
date: invalid option -- 'v'
Try 'date --help' for more information.
Required orbit file dates:  to  ...
Querying ESA POD Hub archive...
--2023-01-20 09:04:01--  https://scihub.copernicus.eu/gnss/search?q=beginPosition:[%20TO%20]%20AND%20endPosition:[%20TO%20]%20AND%20platformname:Sentinel-1%20AND%20filename:S1A_*%20AND%20producttype:AUX_POEORB
Resolving scihub.copernicus.eu (scihub.copernicus.eu)... 146.59.215.226
Connecting to scihub.copernicus.eu (scihub.copernicus.eu)|146.59.215.226|:443... connected.
HTTP request sent, awaiting response... 401 
Authentication selected: Basic realm="Sentinels GNSS RINEX Hub Search"
Reusing existing connection to scihub.copernicus.eu:443.
HTTP request sent, awaiting response... 200 
Length: 499 [application/xml]
Saving to: ‘orbitquery.txt’

orbitquery.txt               100%[============================================>]     499  --.-KB/s    in 0s      

2023-01-20 09:04:02 (149 MB/s) - ‘orbitquery.txt’ saved [499/499]

Checking query for existing orbit file...
if: Missing file name.

**Comment by omarwater98** [comment] 2023-01-24 15:25
> Maybe you are using linux system and need to use `download_sentinel_orbits_linux.csh`?

yes it was that, Thanks

**Closed** 2023-11-30 02:35 UTC
